require: rubocop-rails

AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'Gemfile'
    - 'config.ru'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/**/*.rb'

Style/Documentation:
  Exclude:
    - 'app/**/*.rb'

