require: rubocop-rails

AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'Gemfile'
    - 'config.ru'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/**/*.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/**/*.rb'

Style/Documentation:
  Exclude:
    - 'app/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'app/**/*.rb'

Style/HashSyntax:
  Exclude:
    - 'app/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/**/*.rb'

Layout/LineLength:
  Exclude:
    - 'app/**/*.rb'
